---
- name: "Apache config"
  hosts: labs
  tasks:
    - name: "Apache configuration"
      template:
        src: "templates/inventory.conf.j2"
        dest: "/etc/httpd/conf.d/inventory.conf"
        owner: "apache"
        group: "apache"
      notify: [ "handlers_apache_restart_apache_service" ]

  handlers:
    - name: "handlers_apache_restart_apache_service"
      service:
        name: "httpd"
        state: "restarted"
