---
# Le moteur de template Jinja

- name: "Generate html file for each host"
  hosts: all
  connection: local
  tasks:
   - name: "html file generation"
     template:
      src: "templates/jinja.html.j2"
      dest: "{{playbook_dir}}/{{inventory_hostname}}.html"
