- name: Test variables
  hosts: localhost

  vars:
   prio: playbook_vars

  vars_files:
    - vars_files_prio.yml

  vars_prompt:
    - name: "prio"
      prompt: "A vous :"
      private: no

  tasks:
    - name: Show my variable
      debug:
        msg: "{{ prio }}"