- name: Générer un rapport HTML système avec includes Jinja2
  hosts: all
  gather_facts: yes
  vars:
    support_email: "support@company.com"
    output_file: "/tmp/rapport_systeme.html"

  tasks:

    - name: Récupérer l'uptime
      command: uptime -p
      register: uptime

    - name: Afficher l'uptime transformé
      debug:
        msg: "Uptime (clean) : {{ uptime.stdout | regex_replace('up ', '') }}"

    - name: Générer un rapport HTML
      template:
        src: templates/base.j2
        dest: "{{ output_file }}"

